export const users = [
    { id: 1, firstName: 'John', lastName: 'Cena', email: 'john_cena@gmail.com', country: 'USA', gender: 'Male' },
    { id: 2, firstName: 'Alice', lastName: 'Johnson', email: 'alice.johnson@example.com', country: 'Canada', gender: 'Female' },
    { id: 3, firstName: 'Robert', lastName: 'Smith', email: 'robert.smith@example.com', country: 'UK', gender: 'Male' },
    { id: 4, firstName: 'Maria', lastName: 'Garcia', email: 'maria.garcia@example.com', country: 'Spain', gender: 'Female' },
    { id: 5, firstName: 'David', lastName: 'Lee', email: 'david.lee@example.com', country: 'South Korea', gender: 'Male' },
    { id: 6, firstName: 'Sophie', lastName: 'Brown', email: 'sophie.brown@example.com', country: 'Australia', gender: 'Female' },
    { id: 7, firstName: 'Mohamed', lastName: 'Ali', email: 'mohamed.ali@example.com', country: 'Egypt', gender: 'Male' },
    { id: 8, firstName: 'Chen', lastName: 'Wei', email: 'chen.wei@example.com', country: 'China', gender: 'Male' },
    { id: 9, firstName: 'Liam', lastName: 'Miller', email: 'liam.miller@example.com', country: 'Ireland', gender: 'Male' },
    { id: 10, firstName: 'Ava', lastName: 'Taylor', email: 'ava.taylor@example.com', country: 'USA', gender: 'Female' },
    { id: 11, firstName: 'Noah', lastName: 'Wilson', email: 'noah.wilson@example.com', country: 'New Zealand', gender: 'Male' },
    { id: 12, firstName: 'Emma', lastName: 'Thomas', email: 'emma.thomas@example.com', country: 'Canada', gender: 'Female' },
    { id: 13, firstName: 'Lucas', lastName: 'Moore', email: 'lucas.moore@example.com', country: 'Brazil', gender: 'Male' },
    { id: 14, firstName: 'Isabella', lastName: 'Martin', email: 'isabella.martin@example.com', country: 'France', gender: 'Female' },
    { id: 15, firstName: 'Mason', lastName: 'Clark', email: 'mason.clark@example.com', country: 'USA', gender: 'Male' },
    { id: 16, firstName: 'Mia', lastName: 'Walker', email: 'mia.walker@example.com', country: 'UK', gender: 'Female' },
    { id: 17, firstName: 'Elijah', lastName: 'White', email: 'elijah.white@example.com', country: 'South Africa', gender: 'Male' },
    { id: 18, firstName: 'Charlotte', lastName: 'Hall', email: 'charlotte.hall@example.com', country: 'Australia', gender: 'Female' },
    { id: 19, firstName: 'James', lastName: 'Allen', email: 'james.allen@example.com', country: 'USA', gender: 'Male' },
    { id: 20, firstName: 'Amelia', lastName: 'Young', email: 'amelia.young@example.com', country: 'Ireland', gender: 'Female' },
    { id: 21, firstName: 'Benjamin', lastName: 'King', email: 'benjamin.king@example.com', country: 'Canada', gender: 'Male' },
    { id: 22, firstName: 'Harper', lastName: 'Scott', email: 'harper.scott@example.com', country: 'USA', gender: 'Female' },
    { id: 23, firstName: 'Logan', lastName: 'Green', email: 'logan.green@example.com', country: 'USA', gender: 'Male' },
    { id: 24, firstName: 'Evelyn', lastName: 'Baker', email: 'evelyn.baker@example.com', country: 'UK', gender: 'Female' },
    { id: 25, firstName: 'Henry', lastName: 'Nelson', email: 'henry.nelson@example.com', country: 'USA', gender: 'Male' },
    { id: 26, firstName: 'Abigail', lastName: 'Carter', email: 'abigail.carter@example.com', country: 'Canada', gender: 'Female' },
    { id: 27, firstName: 'Alexander', lastName: 'Mitchell', email: 'alex.mitchell@example.com', country: 'Germany', gender: 'Male' },
    { id: 28, firstName: 'Ella', lastName: 'Perez', email: 'ella.perez@example.com', country: 'Mexico', gender: 'Female' },
    { id: 29, firstName: 'Daniel', lastName: 'Roberts', email: 'daniel.roberts@example.com', country: 'USA', gender: 'Male' },
    { id: 30, firstName: 'Scarlett', lastName: 'Turner', email: 'scarlett.turner@example.com', country: 'UK', gender: 'Female' },
    { id: 31, firstName: 'Matthew', lastName: 'Phillips', email: 'matthew.phillips@example.com', country: 'USA', gender: 'Male' },
    { id: 32, firstName: 'Grace', lastName: 'Campbell', email: 'grace.campbell@example.com', country: 'Canada', gender: 'Female' },
    { id: 33, firstName: 'Jackson', lastName: 'Parker', email: 'jackson.parker@example.com', country: 'USA', gender: 'Male' },
    { id: 34, firstName: 'Chloe', lastName: 'Evans', email: 'chloe.evans@example.com', country: 'Australia', gender: 'Female' },
    { id: 35, firstName: 'Sebastian', lastName: 'Edwards', email: 'sebastian.edwards@example.com', country: 'UK', gender: 'Male' },
    { id: 36, firstName: 'Victoria', lastName: 'Collins', email: 'victoria.collins@example.com', country: 'USA', gender: 'Female' },
    { id: 37, firstName: 'Jack', lastName: 'Stewart', email: 'jack.stewart@example.com', country: 'Scotland', gender: 'Male' },
    { id: 38, firstName: 'Lily', lastName: 'Sanchez', email: 'lily.sanchez@example.com', country: 'Spain', gender: 'Female' },
    { id: 39, firstName: 'Aiden', lastName: 'Morris', email: 'aiden.morris@example.com', country: 'USA', gender: 'Male' },
    { id: 40, firstName: 'Hannah', lastName: 'Rogers', email: 'hannah.rogers@example.com', country: 'Canada', gender: 'Female' },
    { id: 41, firstName: 'Samuel', lastName: 'Reed', email: 'samuel.reed@example.com', country: 'USA', gender: 'Male' },
    { id: 42, firstName: 'Zoe', lastName: 'Cook', email: 'zoe.cook@example.com', country: 'New Zealand', gender: 'Female' },
    { id: 43, firstName: 'Wyatt', lastName: 'Morgan', email: 'wyatt.morgan@example.com', country: 'USA', gender: 'Male' },
    { id: 44, firstName: 'Nora', lastName: 'Bell', email: 'nora.bell@example.com', country: 'Ireland', gender: 'Female' },
    { id: 45, firstName: 'Gabriel', lastName: 'Murphy', email: 'gabriel.murphy@example.com', country: 'UK', gender: 'Male' },
    { id: 46, firstName: 'Riley', lastName: 'Bailey', email: 'riley.bailey@example.com', country: 'USA', gender: 'Female' },
    { id: 47, firstName: 'Nathan', lastName: 'Rivera', email: 'nathan.rivera@example.com', country: 'USA', gender: 'Male' },
    { id: 48, firstName: 'Leah', lastName: 'Cooper', email: 'leah.cooper@example.com', country: 'Canada', gender: 'Female' },
    { id: 49, firstName: 'Julian', lastName: 'Richardson', email: 'julian.richardson@example.com', country: 'USA', gender: 'Male' },
    { id: 50, firstName: 'Aria', lastName: 'Cruz', email: 'aria.cruz@example.com', country: 'Mexico', gender: 'Female' }
  ];

  